#!/bin/bash

sudo apt update
sudo apt upgrade -y

sudo apt install curl -y

# PAQUETES ESENCIALES PARA INSTALAR SWAY EN DEBIAN 13:

sudo apt install -y sway
sudo apt install -y swaybg
sudo apt install -y swaylock
sudo apt install -y swayidle
sudo apt install -y xdg-desktop-portal-wlr
sudo apt install -y waybar
sudo apt install -y wofi
sudo apt install -y foot

sudo apt install -y fonts-noto-color-emoji
sudo apt install -y fonts-noto
sudo apt install -y fonts-dejavu
sudo apt install -y fonts-font-awesome
fc-cache -fv

#Interfaz gráfica para control de volumen
sudo apt install -y pavucontrol

#Paquetes para realizar capturas de pantalla:
sudo apt install -y grim
sudo apt install -y slurp
sudo apt install -y wl-clipboard

#Paquete para instalar las carpetas de usuario:
sudo apt install -y xdg-user-dirs
xdg-user-dirs-update

sudo apt install -y nautilus mousepad firefox-esr
